name: event_queue
description: "Event queue for queuing async tasks."
version: 0.0.1
repository: https://github.com/martinsellergren/event_queue

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
